// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaAcademia.MODEL.Models;

public partial class PlanosTreino
{
    public int Id { get; set; }

    public int TreinadorId { get; set; }

    public int MembroId { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public DateOnly? DataCriacao { get; set; }

    public virtual Membros Membro { get; set; }

    public virtual Treinadores Treinador { get; set; }
}