// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaAcademia.MODEL.Models;

public partial class Treinadores
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public DateOnly DataNascimento { get; set; }

    public string Email { get; set; }

    public string Telefone { get; set; }

    public DateOnly? DataContratacao { get; set; }

    public bool? StatusAtuacao { get; set; }

    public virtual ICollection<PlanosTreino> PlanosTreino { get; set; } = new List<PlanosTreino>();
}